### ISSUE TITLE
More clarification on storage buckets permissions for 3rd party devs

### ISSUE THREAD

**Issue by Duleepa** [googleads/googleads-bidmanager-examples#2]
Hi @jimper, we’ve been chatting with DBM Support but I suspect there’s something being lost in translation as I think the issue is some clarification needed for our use of the DBM API on behalf of our ad clients. We’d like to figure out if this is a problem with the DBM API or transition and whether we are even following the correct methodology! We run reports using our customers’ credentials for reports on DBM and then we analyze the resulting CSV allowing them to do more work in other Google products. This worked great until around July 17-20 and then the report downloading started taking a long time. 

I’m guessing this is due to the move you announced on July 27. Reading through the docs, it is unclear for a service like ours exactly who owns the Google Storage Bucket, is it created by the client in this case and do they need to give our Google Cloud project service account access to that bucket, or can we access it as before with the credentials that they’ve given us? Not quite the forum for this question, but I hope you can help us get some sort of clarity so we can fix. Contact me here or on twitter @dups

**Comment by jimper** [comment]
Hi Duleepa,

There haven't been any changes that would cause reporting slowness. If you have specific examples, your best bet is to work with DBM Support to figure out the root cause. Similarly, for API-specific questions, they're going to be you're best bet; if you aren't getting to a solution, I'd recommend asking them to escalate the case to DBM API support directly.

Regarding storage buckets, if you're accessing those to download reports, that functionality will be going away shortly. Once the new DBM Report Builder is fully enabled, reports will stop being written to those buckets all together. You'll need to modify your workflow to retrieve file download URLs via the API, following the example in our [getting started guide](https://developers.google.com/bid-manager/guides/getting-started-api).

Regards,
- Jonathon Imperiosi, DBM API Team
