### ISSUE TITLE
createquery() Request Body - Which configurations work?

### ISSUE THREAD

**Issue by BenediktMiller** [googleads/googleads-bidmanager-examples#5]
Hello,

I am trying to download reports from the DBM API. I am using createquery() to configure the query for the report, this works well for general reports with metrics like impressions, clicks and costs. I wanted to ask if there is any documentation available on which combinations of report types, groupBys, filters and metrics work with one another? 
Unfortunately the only error the DBM API returns when there is a problem with the query configuration is "backendError", "Woops. We are currently having some issues.". 

For example I am trying to get a report with the metric "METRIC_COOKIE_REACH_AVERAGE_IMPRESSION_FREQUENCY" by using the following request body:

```
{
    "kind":"doubleclickbidmanager#query",
    "metadata":{
       "title":"[API] Title",
       "dataRange":"YEAR_TO_DATE",
       "format":"CSV",
       "sendNotification":false
    },
    "params":{
       "type":"TYPE_REACH_AND_FREQUENCY",
       "groupBys":[
          "FILTER_INSERTION_ORDER"
       ],
       "filters":[
            {
                "type": "FILTER_PARTNER",
                "value": ""
            },
            {
                "type": "FILTER_ADVERTISER",
                "value": ""
            },
            {
                "type": "FILTER_ADVERTISER",
                "value": ""
            },
            {
                "type": "FILTER_ADVERTISER",
                "value": ""
            },
            {
                "type": "FILTER_MEDIA_PLAN",
                "value": ""
            }
       ],
       "metrics":[
            "METRIC_COOKIE_REACH_AVERAGE_IMPRESSION_FREQUENCY"
       ]
    },
    "schedule":{
        "endTimeMs":"0",
        "frequency":"ONE_TIME",
        "nextRunTimezoneCode":"Europe/Berlin"
     }
}
````
(I have removed the filter values because of privacy concerns, but I have confirmed that they work with other report types and metrics. )

createquery() returns the following error:
```
{
   "error":{
      "errors":[
         {
            "domain":"global",
            "reason":"backendError",
            "message":"Woops. We are currently having some issues."
         }
      ],
      "code":503,
      "message":"Woops. We are currently having some issues."
   }
}
```

Why doesn't this query configuration work? Is there any way to get a more meaningful error message?

Any help would be greatly appreciated.

Best regards,
Benedikt Miller

**Comment by jimper** [comment]
Hi Benedikt,

The team is aware of the issue with these generic errors being returned and is working on a fix. That said, configuring queries is quite complicated even with good errors. It's strongly recommended that you build queries in the DBM UI first, as the UI automatically enables/disables fields based on what you've already selected. You can use the API to retrieve queries you've created in the UI, to see what a correct configuration looks like.

In this case the problem seems to be that FILTER_MEDIA_PLAN isn't supported for Reach reports.
If you have any other questions or concerns about configuring reports, please reach out to the [DBM support team](https://developers.google.com/bid-manager/get-support).

Regards,
\- Jonathon Imperiosi, DBM API Team
