### ISSUE TITLE
Doubleclick bid manager - CreateQuery error 

### ISSUE THREAD

**Issue by nlom** [googleads/googleads-bidmanager-examples#7]
Hi 
We are using the DoubleClick bid manager api test page to develop our api.  Got stuck with a a "Whoops. We are currently having some issues".  Here is the Query and the return result.
Have you came across this?  Could you share with me an (any) example Query that actually works (so that we can eliminate any environment/setting issues

api Query
-----------
{
  "kind": "doubleclickbidmanager#query",
  "metadata": {
    "title": "iuj",
    "dataRange": "YEAR_TO_DATE",
    "format": "CSV",
    "sendNotification": false
  },
  "params": {
    "type": "TYPE_REACH_AND_FREQUENCY",
    "groupBys": [
      "FILTER_ADVERTISER"
    ],
    "filters": [
      {
        "type": "FILTER_PARTNER",
        "value": "nn"
      },
      {
        "type": "FILTER_ADVERTISER",
        "value": "mm"
      }
    ],
    "metrics": [
      "METRIC_CLICKS"
    ]
  },
  "schedule": {
    "endTimeMs": 0,
    "frequency": "ONE_TIME",
    "nextRunTimezoneCode": "Europe/Berlin"
  }
}

RETURN ERROR 503
-----------------------
{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "internalError",
    "message": "Woops. We are currently having some issues."
   }
  ],
  "code": 503,
  "message": "Woops. We are currently having some issues."
 }
}

**Comment by jimper** [comment]
Hi there,

Unfortunately the error isn't very specific, but it's likely you've chosen some combination of dimensions/metrics/filters that don't work together. Configuring queries is quite complicated and we strongly recommend doing so in the DV360 UI as a first step, since the UI automatically enables/disables fields based on what you've already selected. You can then use the API to retrieve queries you've created in the UI, to see what a correct configuration looks like.

That said, please reach out to our API support team at dbmapi-support@google.com if you need help debugging specific queries. This tracker is only for issues with the API code samples, but our support team is equipped to help troubleshoot more general API issues.

Regards,
\- Jonathon Imperiosi, DBM API Team
